### PR TITLE
Adaptive timestepping

### PR DESCRIPTION
**Pull request by endJunction**
All prj-files have been formatted automatically because of necessary changes of the time stepping algorithm which was moved.

xmlstarlet is used to move the tag of  `` <time_stepping>`` in all project files. After this moving, project files are formatted automatically with two space indentation. xmlstarlet is then used again to format the files with  with four  space indentation. xmlstarlet commands are
Moving tag: 
```
xmlstarlet ed -m "//OpenGeoSysProject/time_loop/time_stepping" "//OpenGeoSysProject/time_loop/processes/process" foo.prj > new_foo.prj
mv new_foo.prj  foo.prj
```
Format:
```
xmlstarlet fo -s 4 foo.prj > new_foo.prj
mv new_foo.prj  foo.prj
```

### CODE REVIEW

**Comment by wenqing** [comment]
Added a short description about the xmlstarlet.

**Comment by hydromarc** [comment]
Cool, adaptive time stepping! Some questions/comments:
1) What is the meaning of all the new parameters that have to be given in ```<time_stepping>```?
2) Should we maybe start with a more simple setup to test this new implementation? A coupled HT problem seems quite demanding for me...
3) Does the process called ```HeatConduction``` now also contain advection & dispersion?

**Comment by wenqing** [comment]
@waltherm 
1. see the documentation of class EvolutionaryPIDcontroller ufz/ogs#1803.
2. see the fist commit of this PR.
3. it has advection term.

**Comment by hydromarc** [comment]
@wenqing 

1. Sorry, I am to stupid... where exactly can I find the documentation of these parameters?
2. But the first commit contains a coupled HT problem. I was thinking about something very simple, eg. only T diffusion.
3. Then I would plea to rename the process.

**Comment by wenqing** [comment]
@waltherm 
1. Here is the link to doc: https://jenkins.opengeosys.org/job/ufz/job/ogs/job/PR-1803/41/Doxygen/
2. After one of my PRs about staggered coupling, HEAT_CONDUCTION process gets convection term, i.e. grad T *v.
3. I also prefer to rename the class.

**Comment by wenqing** [comment]
@waltherm On the doc web, search `NumLib::EvolutionaryPIDcontroller Class`

**Comment by hydromarc** [comment]
@wenqing thanks for the info!

**Comment by hydromarc** [comment]
@wenqing 
Two more questions:
1) Can you please update the link to the reference? The link is not working for me:
https://doxygen.opengeosys.org/ogs_file_param__prj__time_loop__time_stepping__EvolutionaryPIDcontroller.html
2) I cannot see that any test file is using the time stepping in doxygen; is that a bug or why is this not linked?

**Comment by wenqing** [comment]
@waltherm 
1. I can open the link. or try this:
https://doxygen.opengeosys.org/da/d18/classNumLib_1_1EvolutionaryPIDcontroller.html
2. It is in Data/StaggeredCoupledProcesses/TH/ThermalDensityDrivenFlow2D/, the file name is thermal_gravity_driven_flow2d_adaptive_dt.prj
see: https://github.com/ufz/ogs-data/blob/master/StaggeredCoupledProcesses/TH/ThermalDensityDrivenFlow2D/thermal_gravity_driven_flow2d_adaptive_dt.prj
Besides, there is a PR with two more tests: ufz/ogs#1862.

**Comment by hydromarc** [comment]
1. Yes, this link in doxygen is working, but the referenced literature in there is not:
```Similar algorithm can be found in [1] .```
2. I was looking at https://doxygen.opengeosys.org/ogs_file_param__prj__time_loop__time_stepping__EvolutionaryPIDcontroller.html
There is a section "Used in the following test data files", but no setups are linked there that use this tag.
3. The two linked tests are also coupled problems. No worries, I will set up some simple test cases, as soon as the patches are through.

**Comment by wenqing** [comment]
@waltherm 
1. I do not know why the citation fails. I added an entry in bibliography.bib and cited in the class documentation. @bilke  Is there any other setting for citation in documentation in ogs6?
2. The tag is under a switch case, and  I do not either how to fill that section. There are many others similar places are empty too. Maybe @bilke knows how to. I will update it if there is a solution.

**Comment by endJunction** [comment]
1. Citation is broken due to doxygen. It produces the wrong link for citation.
2. Documentation is wrong: In the prj file the path is `prj/time_loop/processes/process/time_stepping` but in the documentation it is `prj/time_loop/time_stepping`. The latter should be fixed.

**Pull request merged**
